apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
    team: rook
  name: rook-ceph-exporter
  namespace: rook-ceph
spec:
  endpoints:
    - honorLabels: true
      interval: 10s
      path: /metrics
      port: ceph-exporter-http-metrics
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-exporter
      rook_cluster: rook-ceph