---
configOverride: |
  [global]
  mon_allow_pool_delete = true
  mon_warn_on_pool_no_redundancy: "false"
  osd_pool_default_size = 1
  osd_pool_default_min_size = 1

cephClusterSpec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
  resources:
    mgr:
      limits:
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"
    mon:
      limits:
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "512Mi"
    osd:
      limits:
        memory: "2Gi"
      requests:
        cpu: "1000m"
        memory: "1Gi"