---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCaXxLLPYiDGFDxChznHbbfu4KzTWq0kuVHQzVhYSOn5DEgR7A4Iz/gMsdltEgKPvav5LHVtX41Fzz1TJNdvMyEwYWlFdEEOvVpEtdCjaIkg7SgIB6R2AHtE7vfeqiEr5fAQr2+niJjmHJIQkyE0nCtfqteGciXz1iLxKCE92JQKWHTPIQH8Nu0cJFC/pi/jrUeoI18bxFo+xglopIwLRpSFoP4NE119NqbbfTLEoehpQcIDg3FEmKE6M8Yud0B+huyQK9W6OpQDgOCimu8ujUUPbKjrBBFbN4IZhft5UGOVj/kwVjAUCWb+4twqincpLhmff8flrnP3+Sj1qtinXpDPpHrDMh3zDcIfPtZj5VlVJIf8hUoucMxgy+5JU5RAfQIkJt9B57Sf0jnRBWETw3oaZGetOV7c8CHYcBCQZAkI6ZmoGpMR9bVjAk16XKzJGNUqrVbm72iU+vDO+DXmjHYueKiQYkd89HMHfHhW4puRXKEy7Y92HxeQyws1+hqD+yNpdgvjDvwdDwMOU3wsqPZL5Ls1smEc4lYdU2VaaFu19G7nfVmLKeNIgyosXKuaHz8wLjcwxl5ReN9WGjovzUsk3WC9QqEkEhDYX9fjd13U5qfoyVv0lOdttQvyroB7IDP/sRNUnvYzOsCZGvd8gVzw+JRWk6i1enaiZW/tSZCNBKTDaPqOwPGc3KlUwfhKaNxFoupQUYBburcgJUkAmuA8IMxg6qUV4q2LSCKVDabjC4uo4nTqe9S
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
