---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBsSN11n3kB2pYHYx2L2uYaRXzbbMP0Qwp6dzTn7xeNgCy4xVwcY1UnV+jeRNTgZn2v5aNDJyisipn36Uxrc4mSJsJvBcVVIanPjUFA+uciJLUgnQGLsInpBamQxWCSBBN8qLwIp6zEI900jpTlhNOa/n2D1crY1vaViXSGQkl7HXZycSv1j2lH8RHMBTTiGKxyWMpK3aU80MAQWNgx2N+T9W0N55GK0dwCSzfot26TibGFTPfbmTDqr0oLBPMatAEOdFy5FikFjrzkWH+jgdCj0+Qy81O/yAEd1JHuPDwahXyr4jHyWdqcOaNlzY/kXdcfU2vSM6bfCN9MvrLJ0FZ2r50KTe0uFZHjpVDVu59U4YELG5of1cuJBHWZrUlMprHV0StdOnizPCtAV93ZTozPzLrqOmrN6QdGDBdfxcPD41ivBgTD472Iglqq/g+zH7qjuYIIftRA3wN9iZb2W9NYXQuzLmgXaCbE6tlWBj2F66atkLOUF8ulT6YhAV2VBgf3Z4btU2lyMWObRRMuV5LkqMYcDq6vFVOuFDdP7VuROYklSGSHPvPl9LjPFQ7CY/ZfPJ4CKuNr1fknJFQZfOV84dK/XbPknQOVlgtY442V2q4EhddfBuOsZCc7n+R7ioOfM1TrLadHa/EvPfVOxOswN3FSE97A7r1oeuAJFnHVw109m8GkllNuAGPZmnPqcHMjhhCCoOBbMeadl4nEUBNG0wnfD2ezOAo77PqhmcOOMJWfYpDKG2j1
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
