---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zerossl-eab
  namespace: cert-manager
spec:
  encryptedData:
    secret: AgAaCQT0LGGZW4NhmA2Rvw+4G7Pmdvp0eoWB2NlI4ZYHJw8pzT+7o0XH9yp7IKBSI/rYZvWMK2WlnCuM98CX3M11yKd/slhKwJLHvo8AFukxDyKsoBmZdamIUTq2P7DZ8Lo5lv+THKQPSIbSO3Dx7eBLpQLaHbLK4MAm96DCO2eNZzqYGeXIg4z9k1eMqjMa2fvKNufR3nhGewvYu7RommBoxXSaUuR3CGa1LRNBaLSiAWKcueqwkalyYtSMc/ZAxntopUYRKVSmMWqnErwmbH0WdzckZLd27BH4o07AcNVVXPbVxqcdOSoVHqQrZV1iaQd2Ry2pUnq+OTnR8HnEPdtC5exVfpMLR02mO19aJpcoMU3Lyx3E9kw53B8trMb85dsLVR3Nu7uHMx6FF+8in5FhNSaMGx9f98kRpB+MA7Vn/tUIAZ+ygTCXihSvQ9SadMruiVgW9bFX+m6Vm2jiBkY0kJ/QzDZlDRpeJjhiRBXOL6r5erPwrZRSKUWtUfkveLzB0VXBvzfrX/vhLurwc+MjD3ja+MA7WNuJ8iK3ZHshENEe1eStmqa1DsCgApL1lUU/n13QaID8r9eIIZOScTrJ4VVIPUdcCrkngB4jzQV4EXMRruq+3obW3v7Inot27ag2dfEj4eU1BogGtVzythEo70nM3yKYvVNe+H/QgLFKh1AZdjYlT92HBTCCajuA0BdUIj1YeTUhin/0cPE9/nnpVyP+zBRvo5nV6nlUHfzLRCUVXbI29IzUxWVNvd21mEdsV0C2QGJ91BLLqSiAc6mvb4nVUk7BZYpauJxe39QDrIWk7BLh5Q==
  template:
    metadata:
      creationTimestamp: null
      name: zerossl-eab
      namespace: cert-manager
    type: Opaque
