---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-auth0
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgCZmqzMhfbhESdYRlY7p0Kg1zKn58tVEGRwfofVW6KF4V399mwbryEEEfCEsr/PRvhVW05Q6iNXBLfhBg0sXLruNM4ax66AG4zXTS5hz4nw7tSi/IvZkOWUUB8cSPfGL+Wq5EBay8136HxCbf7BNgQHql501iBP8NQTtOlMmQfuXFWpqCMWJ3guW0gTbFjx5PUVt6gzH8Bq2Xf+Mp1nMu48RYlW1QVOlwDR37UqPOZ6k6BnAaAxGbmCjCMQRVY3aSbEIPda/lmOoy69GVSz1DZbUaa8CAmyUBgB6yOI0aZfwcc+KibrT8Z21Qn5WzHvgg1KNSUf3ClWcBHyCgJX+06iuPyb+vYOMLbpbKoZoc6NTGTqKaU/h/Ao/rCMDAD11RdatXNP5vmZzy/10Ug3uZXwiH/1xCQVuz2F98L2qtGmeN/NUPVLnjv38b7jf1b6L2Ca/rcW1qsuFyg1tLCcTP0GEjpKWw/obk3Q1TTmOc4JJIgdPb/cUqlJsOtF2YR1dQdY+L/VpCWQF58S445feEMWAQExnaf//shIIMzEo7UWTV4zHvGokdvQQYm0qwHPyGlgL3QM61TWgizZwghT+QY9p6SwtkV1tOPdpckrlkvfoblskwb2/sphjgRme7HSsu/pSXga5z9peQKWTFGjAm8qtQwfOytpMy+okxO0rYdUexuhD+ustI2ynFPbb30lqhHZTSZWtC41P40qMH/LGN3MDJbUpP9OUUXbmlxqGjpeuA==
    client_secret: AgCEBZO3frpeeqcp9VbBJM3rrCu+dTLq9hXh8XqKFCO5kh1GQHGNxs+nIw6X2UOLmggfAgfD6VlzDqp8qsMeTD27oaxqvGMzz2WnwurIn0YfdBtITnr6cvMZFVee3YxYN+Kc3NE2Ss+lc1/maPoaLFPWNDusfYrgc5iVNjR4GbQDE/K2dVOORzRRtftcT9nHkXahhUxZP+m8KAlUJk5+rMXqfTqnJLgI9bXej6aa6PqSN4gJKcZvvqvtNZXjS3560GWeB8YHNYVX5v9Hk3+D+TnYfR2D+Zcp+K2wKHuuW2M6TEatup0Fenmk4cIP95ewR7rSBFb8ptViyLSMZ43uSVfV7RDmozc9ehjFBYmU67lRVgKYLFdSeoud0GknCckGeNQYoBG2O+QJpj/kTnCDOYTbQEf6YIgPHxgJPvjrvll9qFDaXCVISBH61Y7jbonpfFbuDa7ChGH7w8PE5CjeSEbAyZTMsM2GZWCuT6zkn91aJ+gFBOGT1ANhvSLnH0wp5cKxKK5CFKJ7CPt3ZnrMQH2B1mPL8MGxpYM2zeEYak6ABKpsQz/hcg0tOh6p/NirZzEj8EO6AE8wyjy3XSh1jdBotT9+kT6xdahuNychxMpAKs2qVN6whz+hiGpuC+pf2usNONpHfcnPIvie2Ra6HG7GdY6xki0uMascWEbC4385+0TBWNxG0cvU4n5Avy3M+4OVGypitgNTVDxp6HXWK1zjPCmjkFJ0mPI9KayMvU87TQ69P2FNuWhXO1Gdvxwj/Ml3QsNoU/7E4Aa0361JRQn6
  template:
    metadata:
      creationTimestamp: null
      name: grafana-auth0
      namespace: monitoring
    type: Opaque
