apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-writer
  namespace: monitoring
  annotations:
    argocd.argoproj.io/hook: PreSync # make sure this happens early
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete