apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  description: Applications that are part of configuration of Argo CD.
  sourceRepos:
  - https://github.com/myMarck/kubernetes-helm.git
  - https://bitnami-labs.github.io/sealed-secrets
  - https://charts.jetstack.io
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: cert-manager
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
