apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
spec:
  description: Applications that are part of configuration of Argo CD.
  sourceRepos:
  - https://github.com/myMarck/kubernetes-helm.git
  - https://bitnami-labs.github.io/sealed-secrets
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
