apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
spec:
  description: Applications that are part of configuration of Argo CD.
  sourceRepos:
  - https://github.com/myMarck/kubernetes-configuration.git
  - https://bitnami-labs.github.io/sealed-secrets
  - https://argoproj.github.io/argo-helm
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
