apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: docker-io
  namespace: argocd
stringData:
  url: oci://registry-1.docker.io/bitnamicharts
  name: docker-io
  type: helm
  enableOCI: "true"
  project: infrastructure