apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  description: Applications that are part of configuration of all infrasture applications.
  sourceRepos:
  - https://github.com/myMarck/kubernetes-helm.git
  - https://helm.cilium.io
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
