apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  labels:
    argocd.argoproj.io/bootstrap: "true"
    argocd.argoproj.io/instance: argocd    
spec:
  description: Applications that are part of configuration of all infrasture applications.
  sourceRepos:
  - https://github.com/myMarck/kubernetes-configuration.git
  - https://charts.jetstack.io
  - https://helm.cilium.io
  - https://charts.rook.io/release
  - https://prometheus-community.github.io/helm-charts
  - https://kubernetes.github.io/ingress-nginx
  - https://metallb.github.io/metallb
  - https://argoproj.github.io/argo-helm
  - https://bitnami-labs.github.io/sealed-secrets
  - https://istio-release.storage.googleapis.com/charts
  - https://kiali.org/helm-charts
  - https://grafana.github.io/helm-charts
  - https://aquasecurity.github.io/helm-charts
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  - namespace: cert-manager
    server: https://kubernetes.default.svc
  - namespace: istio-system
    server: https://kubernetes.default.svc
  - namespace: rook-ceph
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: ingress-nginx
    server: https://kubernetes.default.svc
  - namespace: metallb-system
    server: https://kubernetes.default.svc
  - namespace: kiali-operator
    server: https://kubernetes.default.svc
  - namespace: observability
    server: https://kubernetes.default.svc
  - namespace: trivy-system
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
