apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: infrastructure
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /spec/template/spec/containers/0/volumeMounts/0/readOnly
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: '1.16.3'
      helm:
        releaseName: cilium
        valueFiles:
        - $values/helm-values/cilium.yaml
    - repoURL: 'https://github.com/myMarck/kubernetes-configuration.git'
      targetRevision: main
      ref: values      
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
