apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph
      targetRevision: '1.15.5'
      helm:
        valueFiles:
        - $values/rook/ceph-values.yaml
    - repoURL: 'https://github.com/myMarck/kubernetes-configuration.git'
      targetRevision: main
      ref: values      
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
