apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
spec:
  description: Applications that are part of configuration of all infrasture applications.
  sourceRepos:
  - https://github.com/myMarck/kubernetes-configuration.git
  - https://charts.jetstack.io
  - https://helm.cilium.io
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  - namespace: cert-manager
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
