apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: argocd
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: '1.16.1'
      helm:
        releaseName: cert-manager
        valueFiles:
        - $values/cert-manager/values.yaml
    - repoURL: 'https://github.com/myMarck/kubernetes-helm.git'
      targetRevision: main
      ref: values      
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true