apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: argocd
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: '2.16.2'
      helm:
        releaseName: sealed-secrets
        valueFiles:
        - $values/sealed-secrets/values.yaml
    - repoURL: 'https://github.com/myMarck/kubernetes-helm.git'
      targetRevision: main
      ref: values      
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
