apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: infrastructure
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      # https://artifacthub.io/packages/helm/cert-manager/cert-manager
      targetRevision: '1.16.3'
      helm:
        releaseName: cert-manager
        valueFiles:
        - $values/helm-values/cert-manager.yaml
    - repoURL: 'https://github.com/myMarck/kubernetes-configuration.git'
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/myMarck/kubernetes-configuration.git
      path: manifests/cert-manager
      directory:
        include: '*.yaml'
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true