apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  labels:
    argocd.argoproj.io/bootstrap: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: infrastructure
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /spec/template/spec/containers/0/volumeMounts/0/readOnly
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      namespace: kube-system
      name: cilium-agent
      jsonPointers:
        - /spec/endpoints/0/relabelings/0/action        
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      namespace: kube-system
      name: hubble
      jsonPointers:
        - /spec/endpoints/0/relabelings/0/action
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      # https://helm.cilium.io/
      targetRevision: '1.16.6'
      helm:
        releaseName: cilium
        valueFiles:
        - $values/helm-values/cilium.yaml
    - repoURL: 'https://github.com/myMarck/kubernetes-configuration.git'
      targetRevision: main
      ref: values      
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true