apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-tempo
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: '1.14.0'
      helm:
        valueFiles:
        - $values/helm-values/grafana-tempo.yaml
    - repoURL: 'https://github.com/myMarck/kubernetes-configuration.git'
      targetRevision: HEAD
      ref: values      
    - repoURL: https://github.com/myMarck/kubernetes-configuration.git
      path: manifests/grafana-tempo
      directory:
        include: '*.yaml'
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - ServerSideApply=true