apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: k8s-monitoring
      targetRevision: '1.6.16'
      helm:
        valueFiles:
        - $values/helm-values/grafana-cloud.yaml
    - repoURL: 'https://github.com/myMarck/kubernetes-configuration.git'
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/myMarck/kubernetes-configuration.git
      path: manifests/grafana-cloud
      directory:
        include: '*.yaml'
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-cloud
  syncPolicy:
    syncOptions:
      - ServerSideApply=true