apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
  labels:
    argocd.argoproj.io/istio: "true"
spec:
  project: infrastructure
  ignoreDifferences:
    - group: apps
      kind: DaemonSet
      jqPathExpressions:
        - '.spec.template.spec.containers[].env[] | select(.name == "GOMEMLIMIT" or .name == "GOMAXPROCS").valueFrom.resourceFieldRef.divisor'
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: cni
      targetRevision: '1.24.2'
      helm:
        valueFiles:
        - $values/helm-values/istio-cni.yaml
    - repoURL: 'https://github.com/myMarck/kubernetes-configuration.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true