apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: infrastructure
  ignoreDifferences:
    - group: apiextensions.k8s.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
      kind: CustomResourceDefinition
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      # https://artifacthub.io/packages/helm/metallb/metallb
      targetRevision: '0.14.9'
      helm:
        valueFiles:
        - $values/helm-values/metallb.yaml
    - repoURL: 'https://github.com/myMarck/kubernetes-configuration.git'
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/myMarck/kubernetes-configuration.git
      path: manifests/metallb
      directory:
        include: '*.yaml'
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true