apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  labels:
    argocd.argoproj.io/bootstrap: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: infrastructure
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      # https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets
      targetRevision: '2.17.0' 
      helm:
        valueFiles:
        - $values/helm-values/sealed-secrets.yaml
    - repoURL: 'https://github.com/myMarck/kubernetes-configuration.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true    