apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: thanos
      # https://artifacthub.io/packages/helm/bitnami/thanos
      targetRevision: '15.12.0'
      helm:
        valueFiles:
        - $values/helm-values/thanos.yaml
    - repoURL: 'https://github.com/myMarck/kubernetes-configuration.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true