---
controller:
  extraArgs:
    enable-ssl-passthrough: ""
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack