---
namespaceOverride: monitoring
fullnameOverride: kube-prometheus-stack

grafana:
  envValueFrom:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
      secretKeyRef:
        name: grafana-auth0
        key: client_id
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-auth0
        key: client_secret
  grafana.ini:
    auth.generic_oauth:
      enabled: true
      name: Auth0
      allow_sign_up: true
      scopes: openid profile email offline_access
      auth_url: "https://dev-p4z7pma474mi3s2m.eu.auth0.com/authorize"
      token_url: "https://p4z7pma474mi3s2m.eu.auth0.com/oauth/token"
      api_url: "https://p4z7pma474mi3s2m.eu.auth0.com/userinfo"    
      callback_url: "https://grafana.odumsborg.dk/login/generic_oauth"
    server:
      root_url: "https://grafana.odumsborg.dk"
  ingress:
    enabled: true
    hosts:
      - grafana.odumsborg.dk
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.odumsborg.dk
    ingressClassName: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.allow-http: "false"
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-headless.loki.svc.cluster.local:3100
      access: proxy
      basicAuth: false
      orgId: 1
      jsonData:
        httpHeaderName1: X-Scope-OrgID
      secureJsonData:
        httpHeaderValue1: "1"

crds:
  enabled: false
alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.odumsborg.dk
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.odumsborg.dk
    ingressClassName: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.allow-http: "false"
kubeEtcd:
  enabled: true
  service:
    enabled: true
    port: 2379
    targetPort: 2379
    selector:
      component: kube-controller-manager
  serviceMonitor:
    scheme: https
    insecureSkipVerify: false
    serverName: localhost
    caFile: /etc/prometheus/secrets/etcd-certs/ca.crt
    certFile: /etc/prometheus/secrets/etcd-certs/server.crt
    keyFile: /etc/prometheus/secrets/etcd-certs/server.key
prometheus:
  prometheusSpec:
    secrets:
      - etcd-certs
