---
namespaceOverride: monitoring
fullnameOverride: kube-prometheus-stack

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.odumsborg.dk
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.odumsborg.dk
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.allow-http: "false"
crds:
  enabled: false
alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.odumsborg.dk
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.odumsborg.dk
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.allow-http: "false"
kubeEtcd:
  enabled: true
  service:
    enabled: true
    port: 2379
    targetPort: 2379
    selector:
      component: kube-controller-manager
  serviceMonitor:
    scheme: https
    insecureSkipVerify: false
    serverName: localhost
    caFile: /etc/prometheus/secrets/etcd-certs/etcd-ca.crt
    certFile: /etc/prometheus/secrets/etcd-certs/etcd-client.crt
    keyFile: /etc/prometheus/secrets/etcd-certs/etcd-client-key.key
prometheus:
  prometheusSpec:
    secrets:
      - etcd-certs